# Generated by Django 4.2.4 on 2023-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождение"),
        ),
    ]
