# Generated by Django 4.2.4 on 2023-10-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
