# Generated by Django 4.2.4 on 2023-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_imguser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imguser",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="users_img", verbose_name="Фото"
            ),
        ),
    ]
