# Generated by Django 4.2.4 on 2024-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproducts",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
