# Generated by Django 4.2.4 on 2024-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0006_alter_basketproducts_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproducts",
            name="imgage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="basket_product_images",
                verbose_name="Фото",
            ),
        ),
    ]
