# Generated by Django 4.2.4 on 2024-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0007_basketproducts_imgage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basketproducts",
            old_name="imgage",
            new_name="image",
        ),
    ]
