# Generated by Django 4.2.4 on 2024-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0008_rename_imgage_basketproducts_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BasketProductsImg",
        ),
    ]
