# Generated by Django 4.2.4 on 2024-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0009_delete_basketproductsimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproducts",
            name="weight_gram",
            field=models.FloatField(default=0),
        ),
    ]
