# Generated by Django 4.2.4 on 2024-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0010_basketproducts_weight_gram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketproducts",
            name="discount",
        ),
    ]
