# Generated by Django 4.2.4 on 2024-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0011_remove_basketproducts_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproducts",
            name="summ",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
