# Generated by Django 4.2.4 on 2024-02-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketapp", "0012_alter_basketproducts_summ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproducts",
            name="summ",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
