# Generated by Django 4.2.4 on 2023-10-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                (
                    "ingredients",
                    models.CharField(max_length=128, verbose_name="Ингредиенты"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "article_four_hundred",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Артиул 400г"
                    ),
                ),
                (
                    "price_four_hundred",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена 400г"
                    ),
                ),
                (
                    "article_six_hundred",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Артиул 600г"
                    ),
                ),
                (
                    "price_six_hundred",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена 600г"
                    ),
                ),
                (
                    "article_eight_hundred",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Артиул 800г"
                    ),
                ),
                (
                    "price_eight_hundred",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена 800г"
                    ),
                ),
                (
                    "article_one_thousand",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Артиул 1000г"
                    ),
                ),
                (
                    "price_one_thousand",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена 1000г"
                    ),
                ),
                (
                    "article_two_thousand",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Артиул 2000г"
                    ),
                ),
                (
                    "price_two_thousand",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена 2000г"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.productcategories",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ImgProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cakes_images", verbose_name="Фото"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Фото к продуктам",
            },
        ),
    ]
