# Generated by Django 4.2.4 on 2023-11-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
