# Generated by Django 4.2.4 on 2023-08-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategories",
            options={"verbose_name_plural": "Категории"},
        ),
    ]
