# Generated by Django 4.2.4 on 2023-11-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_products_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
