# Generated by Django 4.2.4 on 2024-01-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
