# Generated by Django 4.2.4 on 2023-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_products_description_alter_products_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
