# Generated by Django 4.2.4 on 2024-01-02 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0003_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                ("count", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("discount", models.FloatField(default=0)),
                ("price", models.FloatField()),
                ("summ", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exclusive", "эксклюзив"),
                            ("notexclusive", "не эксклюзив"),
                        ],
                        default="x",
                        max_length=12,
                    ),
                ),
                ("article", models.IntegerField()),
                ("product", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasketProductsImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="basket_product_images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.basketproducts",
                    ),
                ),
            ],
        ),
    ]
