# Generated by Django 4.2.4 on 2023-11-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_products_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(blank=True, default=0, null=True)),
                ("text", models.TextField(verbose_name="Коментарий")),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="count_reviews",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="ReviewsImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="reviews_images")),
                (
                    "review",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.reviews",
                    ),
                ),
            ],
        ),
    ]
