# Generated by Django 4.2.4 on 2023-11-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0005_reviews_products_count_reviews_alter_products_rating_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewsImg",
            new_name="ReviewsImgS",
        ),
    ]
