# Generated by Django 4.2.4 on 2023-11-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_rename_reviewsimg_reviewsimgs"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.products",
            ),
        ),
    ]
