# Generated by Django 4.2.4 on 2024-01-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_basketproducts_basketproductsimg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketproductsimg",
            name="product",
        ),
        migrations.DeleteModel(
            name="BasketProducts",
        ),
        migrations.DeleteModel(
            name="BasketProductsImg",
        ),
    ]
