# Generated by Django 4.2.4 on 2023-11-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_reviews_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="summ_rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
