# Generated by Django 4.2.4 on 2024-01-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_remove_basketproductsimg_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                (
                    "ingredients",
                    models.CharField(max_length=128, verbose_name="Ингредиенты"),
                ),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("rating", models.FloatField(blank=True, default=0, null=True)),
                ("summ_rating", models.FloatField(blank=True, default=0, null=True)),
                (
                    "count_reviews",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.productcategories",
                        verbose_name="Категория",
                    ),
                ),
                ("products", models.ManyToManyField(to="mainapp.baseproduct")),
            ],
        ),
    ]
