# Generated by Django 4.2.4 on 2024-01-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_baseproduct_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImgProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="cakes_images", verbose_name="Фото"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Фото к продуктам--",
            },
        ),
    ]
