# Generated by Django 4.2.4 on 2023-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_products_summ_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("active", "active"), ("notactive", "notactive")],
                default=("notactive", "notactive"),
                max_length=9,
                verbose_name="статус",
            ),
        ),
    ]
