# Generated by Django 4.2.4 on 2024-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_imgproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="article",
            field=models.PositiveIntegerField(
                default=1, unique=True, verbose_name="Артиул"
            ),
            preserve_default=False,
        ),
    ]
