# Generated by Django 4.2.4 on 2024-01-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_baseproduct_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.product",
            ),
        ),
        migrations.DeleteModel(
            name="ImgProducts",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
