# Generated by Django 4.2.4 on 2024-01-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_remove_products_category_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exclusiveproducts",
            name="article",
        ),
        migrations.RemoveField(
            model_name="exclusiveproducts",
            name="price",
        ),
        migrations.AddField(
            model_name="exclusiveproducts",
            name="exclusive",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.baseproduct",
                verbose_name="Эксклюзив",
            ),
            preserve_default=False,
        ),
    ]
