# Generated by Django 4.2.4 on 2024-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_remove_exclusiveproducts_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
