# Generated by Django 4.2.4 on 2023-09-08 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applications",
            old_name="user_name",
            new_name="user",
        ),
        migrations.AddField(
            model_name="applications",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
