# Generated by Django 4.2.4 on 2023-09-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электроная почта"
            ),
        ),
    ]
