# Generated by Django 4.2.4 on 2024-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_applications_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="new",
            field=models.BooleanField(default=True),
        ),
    ]
