# Generated by Django 4.2.4 on 2023-09-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_rename_user_name_applications_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applications",
            name="user",
        ),
    ]
