# Generated by Django 4.2.4 on 2023-09-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_remove_applications_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applications",
            old_name="timestamp",
            new_name="times_send",
        ),
    ]
