# Generated by Django 4.2.4 on 2024-01-18 11:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_completed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "завершенный"),
                            ("notcompleted", "не завершенный"),
                            ("cancelled", "отменённый"),
                        ],
                        default=("notcompleted", "не завершенный"),
                        max_length=12,
                    ),
                ),
                (
                    "status_delivery",
                    models.CharField(
                        blank=True,
                        choices=[("delivery", "доставка"), ("pickup", "самовывоз")],
                        max_length=8,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("discount", models.FloatField(default=0)),
                ("summ", models.FloatField(default=0)),
                ("promo_code", models.CharField(default=None, max_length=100)),
                ("user", models.CharField(max_length=250)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Электроная почта",
                    ),
                ),
                ("index", models.CharField(default="С/в", max_length=50)),
                ("city", models.CharField(default="С/в", max_length=500)),
                ("street", models.CharField(default="С/в", max_length=250)),
                ("num_house", models.CharField(default="С/в", max_length=50)),
                ("num_flat", models.CharField(default="С/в", max_length=50)),
                ("num_building", models.CharField(default="С/в", max_length=50)),
            ],
        ),
    ]
