# Generated by Django 4.2.4 on 2024-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="user_fullname",
        ),
        migrations.AlterField(
            model_name="order",
            name="status_delivery",
            field=models.CharField(
                choices=[("delivery", "доставка"), ("pickup", "самовывоз")],
                max_length=8,
            ),
        ),
    ]
