# Generated by Django 4.2.4 on 2024-01-18 11:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0002_rename_user_order_user_fullname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Электроная почта"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status_completed",
            field=models.CharField(
                choices=[
                    ("completed", "завершенный"),
                    ("notcompleted", "не завершенный"),
                    ("cancelled", "отменённый"),
                ],
                default=("notcompleted", "не завершенный"),
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_fullname",
            field=models.CharField(max_length=250, verbose_name="ФИО"),
        ),
    ]
