# Generated by Django 4.2.4 on 2024-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0004_orderproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(default="С/в", max_length=50),
        ),
    ]
