# Generated by Django 4.2.4 on 2024-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0008_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_code", models.CharField(max_length=50)),
                ("discount", models.FloatField(default=0)),
                ("date", models.DateField()),
            ],
        ),
    ]
