# Generated by Django 4.2.4 on 2024-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0009_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_summ",
            field=models.FloatField(default=0),
        ),
    ]
