# Generated by Django 4.2.4 on 2024-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0010_order_total_summ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_completed",
            field=models.CharField(
                choices=[
                    ("completed", "завершенный"),
                    ("notcompleted", "не завершенный"),
                    ("cancelled", "отменённый"),
                ],
                default=("notcompleted", "не завершенный"),
                max_length=15,
            ),
        ),
    ]
