# Generated by Django 4.2.4 on 2024-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0011_alter_order_status_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="promo_code",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
