# Generated by Django 4.2.4 on 2024-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0014_orderproduct_summ"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_owner",
            field=models.CharField(
                choices=[("user", "пользователь"), ("admin", "администратор")],
                default=("user", "пользователь"),
                max_length=15,
            ),
        ),
    ]
