# Generated by Django 4.2.4 on 2024-01-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0015_order_status_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_completed",
            field=models.CharField(
                choices=[
                    ("completed", "завершенный"),
                    ("notcompleted", "не завершенный"),
                    ("cancelled", "отменённый"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status_owner",
            field=models.CharField(
                choices=[("user", "пользователь"), ("admin", "администратор")],
                default="user",
                max_length=15,
            ),
        ),
    ]
