# Generated by Django 4.2.4 on 2024-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0016_alter_order_status_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="promo_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
