# Generated by Django 4.2.4 on 2024-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0017_alter_promocode_promo_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="index",
            field=models.CharField(default="", max_length=50),
        ),
    ]
