# Generated by Django 4.2.4 on 2024-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0018_alter_order_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="num_building",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="num_flat",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="num_house",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="region",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(default="", max_length=250),
        ),
    ]
