# Generated by Django 4.2.4 on 2024-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0020_alter_order_city_alter_order_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="summ",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_summ",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
