# Generated by Django 4.2.4 on 2024-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0022_alter_order_summ_alter_order_total_summ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="summ",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
